# Generated by Django 4.2.11 on 2024-04-04 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Inventory",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("description", models.TextField(blank=True, null=True)),
                ("quantity_remaining", models.IntegerField(blank=True, null=True)),
                ("quantity_target", models.IntegerField(blank=True, null=True)),
            ],
            options={"db_table": "inventory", "managed": False,},
        ),
        migrations.CreateModel(
            name="MenuItems",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("price", models.FloatField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("category", models.TextField(blank=True, null=True)),
                ("times_ordered", models.IntegerField(blank=True, null=True)),
                ("start_data", models.DateTimeField(blank=True, null=True)),
                ("end_data", models.DateTimeField(blank=True, null=True)),
            ],
            options={"db_table": "menu_items", "managed": False,},
        ),
    ]
